[project]
org-name= "kasun"
version= "0.1.0"

[build-options]
observability-included=true

[dependencies]
"ballerinax/sfdc" = "2.1.2"

[platform]
target = "java8"
	[[platform.libraries]]
	path = "./javalibs/mysql-connector-java-8.0.21.jar"
	modules = ["sfdcoppupdates"]

